name: build-release

on:
  push:
    tags:
      - "*"

jobs:
  base:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Base
        id: build_load_base
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: base.Dockerfile
          target: base
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-base-${{ github.sha }}

  setup-00:
    runs-on: ubuntu-22.04
    needs: [base]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Clean
        id: build_load_clean
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: clean.Dockerfile
          target: clean
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-00
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-00
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-00-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}

  stage-00:
    runs-on: ubuntu-22.04
    needs: [setup-00]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-00
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-00
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-00
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-stage-00-${{ github.sha }}
          build-args: |
            SETUP_IMAGE=sssomeshhh/llvm-br:build-setup-00-${{ github.sha }}

  setup-01:
    runs-on: ubuntu-22.04
    needs: [stage-00]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-00
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-01
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-01
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-01-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-00-${{ github.sha }}

  stage-01:
    runs-on: ubuntu-22.04
    needs: [setup-01]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-01
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-01
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-01
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-stage-01-${{ github.sha }}
          build-args: |
            SETUP_IMAGE=sssomeshhh/llvm-br:build-setup-01-${{ github.sha }}

  setup-02:
    runs-on: ubuntu-22.04
    needs: [stage-01]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-01
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-02
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-02
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-02-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-01-${{ github.sha }}

  stage-02:
    runs-on: ubuntu-22.04
    needs: [setup-02]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-02
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-02
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-02
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-stage-02-${{ github.sha }}
          build-args: |
            SETUP_IMAGE=sssomeshhh/llvm-br:build-setup-02-${{ github.sha }}

  setup-03:
    runs-on: ubuntu-22.04
    needs: [stage-02]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-02
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-03
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-03
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-03-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-02-${{ github.sha }}

  stage-03:
    runs-on: ubuntu-22.04
    needs: [setup-03]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-03
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-03
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-03
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-stage-03-${{ github.sha }}
          build-args: |
            SETUP_IMAGE=sssomeshhh/llvm-br:build-setup-03-${{ github.sha }}

  setup-04:
    runs-on: ubuntu-22.04
    needs: [stage-03]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-03
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-04
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-04
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-04-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-03-${{ github.sha }}

  stage-04:
    runs-on: ubuntu-22.04
    needs: [setup-04]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-04
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-04
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-04
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-stage-04-${{ github.sha }}
          build-args: |
            SETUP_IMAGE=sssomeshhh/llvm-br:build-setup-04-${{ github.sha }}

  end:
    runs-on: ubuntu-22.04
    needs: [stage-04]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load End
        id: build_load_end
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: end.Dockerfile
          target: end
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-04
            type=registry,ref=sssomeshhh/cache:llvm-br-end
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-end
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-end-${{ github.sha }}
          build-args: |
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-04-${{ github.sha }}

  push:
    runs-on: ubuntu-22.04
    needs: [end]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: sssomeshhh
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: push.Dockerfile
          target: push
          push: true
          tags: |
            ghcr.io/sssomeshhh/llvm-builds:${{ github.sha }}
            ghcr.io/sssomeshhh/llvm-builds:${{ github.ref_name }}
          build-args: |
            END_IMAGE=sssomeshhh/llvm-br:build-end-${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs: [end]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  pack-id:
    runs-on: ubuntu-22.04
    needs: [release]
    env:
      END_IMAGE: sssomeshhh/llvm-br:build-end-${{ github.sha }}
    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      - name: Copy ID
        id: copy_id
        run: |
          export DOCKER_BUILKIT=1;
          docker build . --file=pack.Dockerfile --tag=pack:id --target=pack --build-arg END_IMAGE=$END_IMAGE --build-arg X=i;
          docker run --rm --tty --detach --interactive --name=cntnr-id pack:id bash;
          docker cp cntnr-id:/root/llvm/it.xz ./;
          docker stop cntnr-id;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            it.xz
