name: build-release

on:
  push:
    tags:
      - "*"

jobs:
  base:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Base
        id: build_load_base
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: base.Dockerfile
          target: base
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-base-${{ github.sha }}

  setup-00:
    runs-on: ubuntu-22.04
    needs: [base]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Clean
        id: build_load_clean
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: clean.Dockerfile
          target: clean
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-00
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-00
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-00-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}

  stage-00:
    needs: [setup-00]
    uses: ./.github/workflows/stage.yml
    with:
      stage_this: '00'
    secrets: inherit

  setup-01:
    needs: [stage-00]
    uses: ./.github/workflows/setup.yml
    with:
      stage_previous: '00'
      stage_this: '01'
    secrets: inherit

  stage-01:
    needs: [setup-01]
    uses: ./.github/workflows/stage.yml
    with:
      stage_this: '01'
    secrets: inherit

  setup-02:
    needs: [stage-01]
    uses: ./.github/workflows/setup.yml
    with:
      stage_previous: '01'
      stage_this: '02'
    secrets: inherit

  stage-02:
    needs: [setup-02]
    uses: ./.github/workflows/stage.yml
    with:
      stage_this: '02'
    secrets: inherit

  setup-03:
    needs: [stage-02]
    uses: ./.github/workflows/setup.yml
    with:
      stage_previous: '02'
      stage_this: '03'
    secrets: inherit

  stage-03:
    needs: [setup-03]
    uses: ./.github/workflows/stage.yml
    with:
      stage_this: '03'
    secrets: inherit

  setup-04:
    needs: [stage-03]
    uses: ./.github/workflows/setup.yml
    with:
      stage_previous: '03'
      stage_this: '04'
    secrets: inherit

  stage-04:
    needs: [setup-04]
    uses: ./.github/workflows/stage.yml
    with:
      stage_this: '04'
    secrets: inherit

  end:
    runs-on: ubuntu-22.04
    needs: [stage-04]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load End
        id: build_load_end
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: end.Dockerfile
          target: end
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-04
            type=registry,ref=sssomeshhh/cache:llvm-br-end
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-end
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-end-${{ github.sha }}
          build-args: |
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-04-${{ github.sha }}

  push:
    runs-on: ubuntu-22.04
    needs: [end]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: push.Dockerfile
          target: push
          push: true
          tags: |
            ghcr.io/sssomeshhh/llvm-builds:${{ github.sha }}
            ghcr.io/sssomeshhh/llvm-builds:${{ github.ref_name }}
          build-args: |
            END_IMAGE=sssomeshhh/llvm-br:build-end-${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs: [end]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  pack:
    runs-on: ubuntu-22.04
    needs: [release]
    env:
      END_IMAGE: sssomeshhh/llvm-br:build-end-${{ github.sha }}
    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      - name: Copy Dist
        id: copy_dist
        run: |
          export DOCKER_BUILKIT=1;
          docker build . --file=pack.Dockerfile --tag=pack --target=pack --build-arg END_IMAGE=$END_IMAGE;
          docker run --rm --tty --detach --interactive --name=cntnr pack bash;
          docker cp cntnr:/root/llvm/it.xz ./;
          docker stop cntnr;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            it.xz
