name: setup

on:
  workflow_call: 
    inputs:
      stage_previous:
        description: 'Previous Stage Number'
        required: true
        type: string
      stage_this:
        description: 'This Stage Number'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          cache-from: |
            type=registry,ref=sssomeshhh/cache:llvm-br-base
            type=registry,ref=sssomeshhh/cache:llvm-br-stage-${{ inputs.stage_previous }}
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-${{ inputs.stage_this }}
          cache-to: |
            type=registry,ref=sssomeshhh/cache:llvm-br-setup-${{ inputs.stage_this }}
          load: false
          push: true
          tags: |
            sssomeshhh/llvm-br:build-setup-${{ inputs.stage_this }}-${{ github.sha }}
          build-args: |
            BASE_IMAGE=sssomeshhh/llvm-br:build-base-${{ github.sha }}
            STAGE_IMAGE=sssomeshhh/llvm-br:build-stage-${{ inputs.stage_previous }}-${{ github.sha }}
